export const aiIntegrationNotebook = {
  metadata: { title: "AI Agent Integration", created: Date.now() },
  cells: [
    {
      id: "ai-1",
      type: "markdown",
      source: [
        "## Capabilities",
        "",
        "1. **Inline completions** — Ghost text predictions as you type (VS Code-style)",
        "2. **Cell rewriting** — Select text, ask AI to improve or translate",
        "3. **Cell generation** — Generate new cells from a prompt",
        "4. **Chat sidebar** — Conversational AI panel",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "ai-2",
      type: "code",
      source: [
        "interface AICompletionProvider {",
        "  id: string;",
        "  name: string;",
        "  supportsStreaming: boolean;",
        "",
        "  getCompletions(req: CompletionRequest): Promise<CompletionResponse>;",
        "  cancel?(requestId: string): void;",
        "  isAvailable(): Promise<boolean>;",
        "}",
      ].join("\n"),
      metadata: { language: "typescript" },
      outputs: [],
    },
    {
      id: "ai-3",
      type: "markdown",
      source: [
        "## Ghost Text",
        "",
        "The completion appears as semi-transparent text after the cursor.",
        "",
        "| Action | Key | Effect |",
        "|--------|-----|--------|",
        "| Accept all | `Tab` | Insert full ghost text |",
        "| Accept word | `Cmd+Right` | Insert next word |",
        "| Reject | `Escape` | Dismiss |",
        "| Ignore | Keep typing | New request |",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "ai-4",
      type: "markdown",
      source: [
        "## Security and Privacy",
        "",
        "- **API keys** are never stored in the notebook document",
        "- **Context** is limited to a configurable window (default: 5 before, 2 after)",
        "- **No telemetry** — all requests go directly to your configured provider",
        "- **Local-first** — works with Ollama, LM Studio, vLLM out of the box",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
  ],
};
