export const dataModelNotebook = {
  metadata: { title: "Data Model Explorer", created: Date.now() },
  cells: [
    {
      id: "dm-1",
      type: "markdown",
      source: [
        "## Notebook Structure",
        "",
        "A **Notebook** is the top-level container with metadata and an ordered array of cells.",
        "",
        "```typescript",
        "interface Notebook {",
        "  metadata: NotebookMetadata;",
        "  cells: Cell[];",
        "}",
        "",
        "interface NotebookMetadata {",
        "  title: string;",
        "  created: number;",
        "  modified: number;",
        "  tags?: string[];",
        "  pluginData?: Record<string, unknown>;",
        "}",
        "```",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "dm-2",
      type: "code",
      source: [
        "// Core Cell interface",
        "interface Cell {",
        '  id: string;           // nanoid(12) — URL-safe, collision-resistant',
        '  type: CellType;       // "markdown"|"code"|"latex"|"table"|"image"|"embed"|"mermaid"|"raw"',
        "  source: string;       // raw content (always a string)",
        "  metadata: CellMetadata;",
        "  outputs: CellOutput[];",
        "  editing?: boolean;    // per-cell edit/view mode flag",
        "}",
        "",
        "type CellType = ",
        '  | "markdown" | "code" | "raw" | "latex"',
        '  | "table" | "image" | "embed" | "mermaid"',
        "  | string; // plugins can register custom types",
      ].join("\n"),
      metadata: { language: "typescript" },
      outputs: [],
    },
    {
      id: "dm-3",
      type: "code",
      source: [
        "// Cell outputs (code execution results)",
        "interface CellOutput {",
        '  outputType: "stdout" | "stderr" | "result" | "error" | "display";',
        "  content: string;",
        '  mimeType?: string;  // e.g. "text/plain", "text/html", "image/png"',
        "  timestamp?: number;",
        "}",
        "",
        "// Cell metadata (extensible per cell type)",
        "interface CellMetadata {",
        "  language?: string;    // code cells: programming language",
        "  collapsed?: boolean;  // whether outputs are collapsed",
        "  trusted?: boolean;    // embed cells: skip sanitization",
        "  executionCount?: number;",
        "  [key: string]: unknown; // plugin-specific metadata",
        "}",
      ].join("\n"),
      metadata: { language: "typescript" },
      outputs: [],
    },
    {
      id: "dm-4",
      type: "markdown",
      source: [
        "## Cell Types",
        "",
        "| Type | Purpose | Source Format |",
        "|------|---------|---------------|",
        "| `markdown` | Rich text content | CommonMark + GFM |",
        "| `code` | Source code with highlighting | Plain text |",
        "| `latex` | Math formulas | LaTeX `$$...$$` syntax |",
        "| `table` | Tabular data | Pipe-separated Markdown |",
        "| `image` | Images | Base64 data URI or URL |",
        "| `embed` | External content | JSON `{strategy, ...}` |",
        "| `mermaid` | Diagrams | Mermaid DSL |",
        "| `raw` | Unprocessed text | Plain text |",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "dm-5",
      type: "code",
      source: [
        "// Table cell data format (stored as pipe-separated markdown)",
        "// | Name | Age | City |",
        "// | --- | --- | --- |",
        "// | Alice | 30 | NYC |",
        "",
        "// Image cell source format",
        'const imageSource = "data:image/png;base64,iVBOR...";',
        "// or URL: imageSource = 'https://example.com/img.png'",
        "",
        "// Embed cell source format (JSON string)",
        'const embedSource = JSON.stringify({',
        '  strategy: "iframe", // or "html" | "component"',
        '  url: "https://example.com/widget",',
        "  height: 400,",
        '  sandbox: "allow-scripts"',
        "});",
      ].join("\n"),
      metadata: { language: "typescript" },
      outputs: [],
    },
    {
      id: "dm-6",
      type: "code",
      source: [
        "// Complete serialization example",
        "const notebook = {",
        "  metadata: {",
        '    title: "Quantum Mechanics Notes",',
        "    created: 1700000000000,",
        "    modified: 1700001000000,",
        '    tags: ["physics", "quantum"]',
        "  },",
        "  cells: [",
        '    { id: "abc123def456", type: "markdown",',
        '      source: "# Introduction\\nWelcome to...",',
        "      metadata: {}, outputs: [] },",
        '    { id: "ghi789jkl012", type: "code",',
        '      source: "const h = 6.626e-34;",',
        '      metadata: { language: "javascript" },',
        '      outputs: [{ outputType: "result",',
        '        content: "6.626e-34", mimeType: "text/plain" }] },',
        '    { id: "mno345pqr678", type: "latex",',
        '      source: "$$E = \\\\hbar\\\\omega$$",',
        "      metadata: {}, outputs: [] }",
        "  ]",
        "};",
      ].join("\n"),
      metadata: { language: "typescript" },
      outputs: [],
    },
    {
      id: "dm-7",
      type: "markdown",
      source: [
        "## Key Design Decisions",
        "",
        "- **IDs are `nanoid(12)`** — 12 chars, URL-safe, ~143 bits entropy, collision-resistant",
        "- **Source is always a string** — even tables and images use string encoding for uniform serialization",
        "- **Metadata is extensible** — plugins store arbitrary data via `[key: string]: unknown`",
        "- **Outputs are append-only** — code cells accumulate execution results over time",
        "- **No circular references** — notebooks are safely `JSON.stringify`-able",
        "- **Structural sharing** — undo history only clones modified cells, not the entire notebook",
        "",
        "## Validation",
        "",
        "- Every cell must have a non-empty `id` (unique within the notebook)",
        "- `type` must be a registered cell type (built-in or plugin-defined)",
        "- `source` must be a string (empty string is valid)",
        "- `outputs` must be an array (empty array for non-code cells)",
        "- Notebook must have at least one cell",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
  ],
};
