export const editorEngineNotebook = {
  metadata: { title: "Editor Engine & Dual-Mode System", created: Date.now() },
  cells: [
    {
      id: "ee-1",
      type: "markdown",
      source: [
        "# Editor Engine & Dual-Mode System",
        "",
        "The editor engine is the central orchestrator — **pure TypeScript**, no DOM, no framework.",
        "",
        "## Responsibilities",
        "",
        "1. **Cell lifecycle** — create, delete, move, split, merge cells",
        "2. **Dual-mode toggle** — per-cell edit/view switching",
        "3. **Selection model** — which cell is focused, text cursor position",
        "4. **Undo/Redo** — command-based history with configurable depth",
        "5. **Keybinding system** — extensible keyboard shortcuts",
        "6. **Clipboard** — copy/cut/paste cells or cell content",
        "7. **Drag & drop** — reorder cells via drag handle",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "ee-config",
      type: "code",
      source: [
        "interface EditorEngineConfig {",
        "  maxHistory?: number;        // Maximum undo history depth (default: 100)",
        "  defaultCellType?: CellType; // Default cell type for new cells",
        "  startInEditMode?: boolean;  // Whether to start all cells in edit mode",
        "  keybindings?: Partial<KeybindingMap>;",
        "  plugins?: SciNotebookPlugin[];",
        "}",
        "",
        "class EditorEngine {",
        "  constructor(notebook: Notebook, config?: EditorEngineConfig);",
        "}",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ee-api-notebook",
      type: "code",
      source: [
        "// --- Notebook access ---",
        "getNotebook(): Readonly<Notebook>;",
        "getCell(id: string): Readonly<Cell> | undefined;",
        "getCells(): ReadonlyArray<Cell>;",
        "",
        "// --- Cell CRUD ---",
        "insertCell(index: number, type?: CellType): Cell;",
        "insertCellAfter(refId: string, type?: CellType): Cell;",
        "insertCellBefore(refId: string, type?: CellType): Cell;",
        "deleteCell(id: string): void;",
        "deleteCells(ids: string[]): void;",
        "moveCell(id: string, toIndex: number): void;",
        "duplicateCell(id: string): Cell;",
        "",
        "// --- Cell content ---",
        "updateCellSource(id: string, source: string): void;",
        "updateCellMetadata(id: string, meta: Partial<CellMetadata>): void;",
        "setCellType(id: string, type: CellType): void;",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ee-api-mode",
      type: "code",
      source: [
        "// --- Dual mode ---",
        "setEditMode(cellId: string): void;",
        "setViewMode(cellId: string): void;",
        "toggleMode(cellId: string): void;",
        "setAllEditMode(): void;",
        "setAllViewMode(): void;",
        'getMode(cellId: string): "edit" | "view";',
        "",
        "// --- Selection ---",
        "focusCell(id: string): void;",
        "getFocusedCellId(): string | null;",
        "selectCells(ids: string[]): void;",
        "getSelectedCellIds(): string[];",
        "clearSelection(): void;",
        "",
        "// --- History ---",
        "undo(): void;",
        "redo(): void;",
        "canUndo(): boolean;",
        "canRedo(): boolean;",
        "checkpoint(label?: string): void;",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ee-api-clipboard",
      type: "code",
      source: [
        "// --- Clipboard ---",
        "copyCells(ids: string[]): void;",
        "cutCells(ids: string[]): void;",
        "pasteCells(afterId?: string): Cell[];",
        "",
        "// --- Split / Merge ---",
        "splitCell(id: string, cursorOffset: number): [Cell, Cell];",
        "mergeCellUp(id: string): Cell | null;",
        "mergeCellDown(id: string): Cell | null;",
        "",
        "// --- Drag & Drop ---",
        "startDrag(cellId: string): void;",
        "dragOver(targetIndex: number): void;",
        "endDrag(): void;",
        "cancelDrag(): void;",
        "getDragState(): { dragging: boolean; cellId: string | null; targetIndex: number | null };",
        "",
        "// --- Lifecycle ---",
        "destroy(): void;",
        "",
        "// --- Event Bus (delegate) ---",
        "on<T extends EventType>(type: T, handler: EventHandler<T>): Unsubscribe;",
        "emit<T extends EventType>(type: T, payload: EventPayload<T>): void;",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ee-dual-mode",
      type: "markdown",
      source: [
        "## Dual-Mode System",
        "",
        "Each cell independently tracks its mode (`editing` field on the Cell model).",
        "",
        "**Edit mode:**",
        "- The cell renders a text editor (textarea, CodeMirror, Monaco, or adapter-provided input)",
        "- Raw Markdown/LaTeX/Mermaid source is visible",
        "- Syntax highlighting is active (via adapter or plugin)",

        "",
        "**View mode:**",
        "- The cell's `source` is passed through the rendering pipeline",
        "- The rendered output (HTML) replaces the editor",
        "- Clicking the rendered cell switches it back to edit mode",
        "",
        "### Mode Transitions",
        "",
        "```",
        "┌──────────┐  click / Enter / dblclick  ┌──────────┐",
        "│   VIEW   │ ─────────────────────────► │   EDIT   │",
        "│   mode   │                            │   mode   │",
        "│          │ ◄───────────────────────── │          │",
        "└──────────┘  Escape / blur / Cmd+Enter └──────────┘",
        "```",
        "",
        "### Notebook-Level Mode",
        "",
        "- `setAllEditMode()` — every cell enters edit mode (raw MD view)",
        "- `setAllViewMode()` — every cell enters view mode (rendered)",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "ee-selection",
      type: "code",
      source: [
        "// Selection Model",
        "interface SelectionState {",
        "  focusedCellId: string | null;",
        "  selectedCellIds: Set<string>;",
        "  cursorOffset: number | null;",
        "  textSelection: { start: number; end: number } | null;",
        "}",
        "",
        "// Navigation rules:",
        "// ArrowUp at top of cell → focus previous cell (cursor at end)",
        "// ArrowDown at bottom → focus next cell (cursor at start)",
        "// Shift+ArrowUp/Down → extend cell selection",
        "// Cmd/Ctrl+A → select all cells",
        "// Tab → indent (edit mode) or focus next cell (view mode)",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ee-history",
      type: "code",
      source: [
        "// Undo/Redo — Command Pattern",
        "interface Command {",
        "  label: string;",
        "  execute(): void;",
        "  undo(): void;",
        "}",
        "",
        "// Rapid keystrokes batched into one undo entry (debounce 300ms)",
        "// checkpoint() forces a new undo boundary",
        "",
        "// HistoryManager maintains a stack of Command objects",
        "// maxHistory limits the stack depth (default: 100)",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ee-keybindings",
      type: "markdown",
      source: [
        "## Default Keybindings",
        "",
        "| Key | Action | Context |",
        "|-----|--------|---------|",
        "| `Enter` | Enter edit mode on focused cell | view mode |",
        "| `Escape` | Exit edit mode | edit mode |",
        "| `Cmd+Enter` | Run cell & advance (if plugin) | edit mode |",
        "| `Shift+Enter` | Exit edit mode & focus next | edit mode |",
        "| `ArrowUp/Down` | Navigate cells | view mode |",
        "| `Cmd+Shift+D` | Delete focused cell | any |",
        "| `Cmd+Shift+ArrowUp` | Move cell up | any |",
        "| `Cmd+Shift+ArrowDown` | Move cell down | any |",
        "| `Cmd+Z` | Undo | any |",
        "| `Cmd+Shift+Z` | Redo | any |",
        "| `Cmd+B` | Toggle bold (insert `**`) | edit mode |",
        "| `Cmd+I` | Toggle italic (insert `*`) | edit mode |",
        "| `Cmd+K` | Insert link | edit mode |",
        "| `Cmd+/` | Toggle cell type (md / code) | any |",
        "",
        "Plugins can register additional keybindings via `plugin.keybindings`.",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "ee-split-merge",
      type: "markdown",
      source: [
        "## Cell Split & Merge",
        "",
        "**Split** (`Cmd+Shift+Enter`): source is split at `cursorOffset`, original keeps text before cursor, new cell gets text after. Both inherit the same type.",
        "",
        "**Merge Up** (`Backspace` at cell start): current cell's source appended to previous, current deleted.",
        "",
        "**Merge Down** (`Delete` at cell end): symmetric to merge up.",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "ee-events",
      type: "code",
      source: [
        "// Event Bus — all events",
        "type EventType =",
        '  | "cell:created" | "cell:deleted" | "cell:updated"',
        '  | "cell:moved" | "cell:mode-changed" | "cell:focused"',
        '  | "selection:changed"',
        '  | "history:undo" | "history:redo" | "history:checkpoint"',
        '  | "notebook:updated"',
        '  | "plugin:registered" | "plugin:unregistered"',
        "  | string; // plugins can emit custom events",
        "",
        "// Bus is synchronous by default.",
        "// Async listeners can wrap in queueMicrotask.",
        "",
        "// Drag & Drop: actual DOM drag handling is implemented by",
        "// each framework adapter. The engine only tracks state",
        '// and emits "cell:moved" events.',
      ].join("\n"),
      metadata: { language: "typescript" },
    },
  ],
};
