export const exportPluginsNotebook = {
  metadata: { title: "Export Plugins", created: Date.now() },
  cells: [
    {
      id: "ep-intro",
      type: "markdown",
      source: [
        "# Export Plugins (PDF & DOCX)",
        "",
        "Export notebooks to PDF and DOCX formats using `@velo-sci/notebook-plugin-export`.",
        "",
        "## Installation",
        "",
        "```bash",
        "pnpm add @velo-sci/notebook-plugin-export",
        "```",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "ep-plugin-usage",
      type: "code",
      source: [
        "// As a Plugin",
        'import { createExportPlugin } from "@velo-sci/notebook-plugin-export";',
        "",
        "const engine = createNotebook({",
        "  notebook: myNotebook,",
        "  config: {",
        "    plugins: [createExportPlugin()],",
        "  },",
        "});",
        "",
        "// Trigger via events",
        'engine.emit("export:pdf", { notebook: engine.getNotebook() });',
        'engine.emit("export:docx", { notebook: engine.getNotebook() });',
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ep-standalone",
      type: "code",
      source: [
        "// Standalone Functions",
        "import {",
        "  exportToPDF,",
        "  exportToDOCX,",
        "  generatePrintHTML,",
        "  downloadDOCX,",
        '} from "@velo-sci/notebook-plugin-export";',
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ep-pdf",
      type: "markdown",
      source: "## PDF Export",
      metadata: {},
    },
    {
      id: "ep-pdf-browser",
      type: "code",
      source: [
        "// Browser Print-to-PDF",
        'import { exportToPDF } from "@velo-sci/notebook-plugin-export";',
        "",
        "exportToPDF(notebook, {",
        '  pageSize: "A4",          // \'A4\' | \'letter\' | \'legal\'',
        '  orientation: "portrait", // \'portrait\' | \'landscape\'',
        "  margins: { top: 20, right: 20, bottom: 20, left: 20 },",
        "  includeHeader: true,",
        "  includeFooter: true,",
        '  headerText: "My Notebook",',
        '  footerText: "Page {page}",',
        "});",
        "",
        "// Opens the browser's print dialog. User can then save as PDF.",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ep-pdf-headless",
      type: "code",
      source: [
        "// Headless Browser (Puppeteer / Playwright)",
        'import { generatePrintHTML } from "@velo-sci/notebook-plugin-export";',
        "",
        "const html = generatePrintHTML(notebook, {",
        '  pageSize: "A4",',
        '  orientation: "portrait",',
        "});",
        "",
        "// Use with Puppeteer",
        "const browser = await puppeteer.launch();",
        "const page = await browser.newPage();",
        "await page.setContent(html);",
        'await page.pdf({ path: "output.pdf", format: "A4" });',
        "await browser.close();",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ep-docx",
      type: "markdown",
      source: "## DOCX Export",
      metadata: {},
    },
    {
      id: "ep-docx-code",
      type: "code",
      source: [
        "// Generate and Download",
        'import { exportToDOCX, downloadDOCX } from "@velo-sci/notebook-plugin-export";',
        "",
        "// Generate DOCX content (Office Open XML)",
        "const docx = exportToDOCX(notebook);",
        "",
        "// Download directly",
        'downloadDOCX(notebook, "my-notebook.docx");',
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "ep-docx-mapping",
      type: "markdown",
      source: [
        "### Supported Formatting",
        "",
        "The DOCX export preserves:",
        "",
        "| Element | DOCX Mapping |",
        "|---------|-------------|",
        "| `# Heading 1` | Heading 1 style |",
        "| `## Heading 2` | Heading 2 style |",
        "| `### Heading 3` | Heading 3 style |",
        "| `**bold**` | Bold run |",
        "| `*italic*` | Italic run |",
        "| `` `code` `` | Monospaced font |",
        "| `> blockquote` | Indented paragraph |",
        "| `- list item` | Bulleted list |",
        "| Code blocks | Monospaced paragraph with background |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "ep-plugin-events",
      type: "markdown",
      source: [
        "## Plugin Events",
        "",
        "When using `createExportPlugin()`, the plugin listens for these events:",
        "",
        "| Event | Payload | Action |",
        "|-------|---------|--------|",
        "| `export:pdf` | `{ notebook }` | Calls `exportToPDF()` |",
        "| `export:docx` | `{ notebook }` | Calls `downloadDOCX()` |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "ep-api",
      type: "markdown",
      source: [
        "## API Reference",
        "",
        "- **`exportToPDF(notebook, options?)`** — Opens the browser print dialog with a print-optimized HTML view",
        "- **`generatePrintHTML(notebook, options?)`** — Returns a standalone HTML string for headless PDF generation",
        "- **`exportToDOCX(notebook)`** — Returns the DOCX file content as a string (Office Open XML)",
        "- **`downloadDOCX(notebook, filename?)`** — Generates and triggers a browser download",
        "- **`createExportPlugin()`** — Returns a `SciNotebookPlugin` that registers event handlers",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "ep-options",
      type: "code",
      source: [
        "// PDFExportOptions",
        "interface PDFExportOptions {",
        '  pageSize?: "A4" | "letter" | "legal";',
        '  orientation?: "portrait" | "landscape";',
        "  margins?: { top: number; right: number; bottom: number; left: number };",
        "  includeHeader?: boolean;",
        "  includeFooter?: boolean;",
        "  headerText?: string;",
        "  footerText?: string;",
        "}",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
  ],
};
