export const frameworkAdaptersNotebook = {
  id: "doc-framework-adapters",
  title: "Framework Adapters & Public API",
  cells: [
    {
      id: "fa-intro",
      type: "markdown",
      source: [
        "# Framework Adapters & Public API",
        "",
        "The core library (`@velo-sci/notebook-core`) is **framework-agnostic**.",
        "Framework adapters are thin wrappers that bridge the core engine to a",
        "specific UI framework's component model, lifecycle, and reactivity system.",
        "",
        "Each adapter is a separate package:",
        "",
        "| Package | Framework | Status |",
        "|---------|-----------|--------|",
        "| `@velo-sci/notebook-react` | React 18+ | ✅ Primary |",
        "| `@velo-sci/notebook-vue` | Vue 3+ | ✅ Implemented |",
        "| `@velo-sci/notebook-svelte` | Svelte 5+ | ✅ Implemented |",
        "| `@velo-sci/notebook-vanilla` | Vanilla JS | ✅ Primary |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "fa-responsibilities",
      type: "markdown",
      source: [
        "## Adapter Responsibilities",
        "",
        "1. **Mount the editor** into a DOM container",
        "2. **Render cells** using the framework's component model",
        "3. **Bind events** from the core engine to framework reactivity",
        "4. **Provide text editors** (textarea, CodeMirror, Monaco) for edit mode",
        "5. **Hydrate plugin output** (Mermaid SVGs, component embeds)",
        "6. **Expose a framework-idiomatic API** (hooks for React, composables for Vue)",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "fa-core-api",
      type: "markdown",
      source: "## Core Public API (`@velo-sci/notebook-core`)",
      metadata: {},
    },
    {
      id: "fa-core-code",
      type: "code",
      source: [
        "// createNotebook — main entry point",
        "function createNotebook(options?: CreateNotebookOptions): EditorEngine;",
        "",
        "interface CreateNotebookOptions {",
        "  /** Initial notebook document (or creates empty) */",
        "  notebook?: Notebook;",
        "  /** Plugins to register */",
        "  plugins?: SciNotebookPlugin[];",
        "  /** Editor engine configuration */",
        "  editor?: EditorEngineConfig;",
        "  /** Rendering pipeline configuration */",
        "  rendering?: {",
        "    parser?: MarkdownParser;",
        "    sanitize?: boolean;",
        "    cacheSize?: number;",
        "  };",
        '  /** Theme ("light" | "dark" | custom CSS variables object) */',
        "  theme?: string | Record<string, string>;",
        "}",
        "",
        "// Load and migrate a notebook from JSON",
        "function loadNotebook(json: string | object): Notebook;",
        "",
        "// Serialize a notebook to JSON",
        "function saveNotebook(notebook: Notebook, pretty?: boolean): string;",
        "",
        "// Validate a notebook document",
        "function validateNotebook(doc: unknown): ValidationResult;",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "fa-react-title",
      type: "markdown",
      source: "## React Adapter (`@velo-sci/notebook-react`)",
      metadata: {},
    },
    {
      id: "fa-react-component",
      type: "code",
      source: [
        "// <SciNotebook> — primary React component",
        'import { SciNotebook } from "@velo-sci/notebook-react";',
        'import { latexPlugin } from "@velo-sci/notebook-plugin-latex";',
        'import { mermaidPlugin } from "@velo-sci/notebook-plugin-mermaid";',
        "",
        "function App() {",
        "  return (",
        "    <SciNotebook",
        "      notebook={initialNotebook}",
        "      plugins={[latexPlugin(), mermaidPlugin()]}",
        '      theme="dark"',
        "      onChange={(notebook) => console.log('Updated:', notebook)}",
        "      onCellFocus={(cellId) => console.log('Focused:', cellId)}",
        '      className="my-notebook"',
        "    />",
        "  );",
        "}",
      ].join("\n"),
      metadata: { language: "tsx" },
    },
    {
      id: "fa-react-props",
      type: "code",
      source: [
        "// SciNotebookProps — full props interface",
        "interface SciNotebookProps {",
        "  notebook?: Notebook;",
        "  plugins?: SciNotebookPlugin[];",
        '  theme?: "light" | "dark" | string;',
        "  onChange?: (notebook: Notebook) => void;",
        "  onCellFocus?: (cellId: string | null) => void;",
        '  onCellModeChange?: (cellId: string, mode: "edit" | "view") => void;',
        "  readOnly?: boolean;",
        "  showToolbar?: boolean;",
        "  showCellTypes?: boolean;",
        "  showDragHandles?: boolean;",
        "  showCellActions?: boolean;",
        "  toolbarItems?: PluginToolbarItem[];",
        "  className?: string;",
        "  style?: React.CSSProperties;",
        '  editorType?: "textarea" | "codemirror" | "monaco";',
        "  engineRef?: React.Ref<EditorEngine>;",
        "}",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "fa-react-hooks",
      type: "code",
      source: [
        "// React Hooks — use inside the <SciNotebook> component tree",
        "",
        "// Access the EditorEngine from within the notebook tree",
        "function useSciNotebook(): EditorEngine;",
        "",
        "// Get the current notebook state (reactive)",
        "function useNotebook(): Readonly<Notebook>;",
        "",
        "// Get a specific cell (reactive)",
        "function useCell(cellId: string): Readonly<Cell> | undefined;",
        "",
        "// Get the focused cell ID (reactive)",
        "function useFocusedCell(): string | null;",
        "",
        "// Subscribe to engine events",
        "function useNotebookEvent<T extends EventType>(",
        "  type: T,",
        "  handler: (payload: EventPayload<T>) => void",
        "): void;",
        "",
        "// Get the rendering pipeline output for a cell",
        "function useRenderedCell(cellId: string): RenderedCell | null;",
        "",
        "// Access plugin data",
        "function usePluginData<T = unknown>(pluginId: string, key: string): T | undefined;",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "fa-react-custom-renderer",
      type: "code",
      source: [
        "// Custom Cell Renderers (React)",
        'import { registerCellRenderer } from "@velo-sci/notebook-react";',
        "",
        "// Register a custom React component for a cell type",
        'registerCellRenderer("my-widget", ({ cell, isEditing, onUpdate }) => {',
        "  if (isEditing) {",
        "    return (",
        "      <textarea",
        "        value={cell.source}",
        "        onChange={(e) => onUpdate(e.target.value)}",
        "      />",
        "    );",
        "  }",
        "  return <MyWidgetPreview data={JSON.parse(cell.source)} />;",
        "});",
      ].join("\n"),
      metadata: { language: "tsx" },
    },
    {
      id: "fa-vue-title",
      type: "markdown",
      source: [
        "## Vue 3+ Adapter (`@velo-sci/notebook-vue`)",
        "",
        "The Vue adapter uses render functions (no SFC) so it can be built with tsup without a Vue compiler.",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "fa-vue-code",
      type: "code",
      source: [
        "// Vue 3+ — mounting with render functions",
        "import { createApp, h } from 'vue';",
        "import { SciNotebook } from '@velo-sci/notebook-vue';",
        "",
        "const app = createApp({",
        "  render() {",
        "    return h(SciNotebook, {",
        "      notebook: myNotebook,",
        "      theme: 'dark',",
        "      showToolbar: true,",
        "      showTOC: true,",
        "      readOnly: false,",
        "      onChange: (nb) => console.log('Updated:', nb),",
        "    });",
        "  },",
        "});",
        "app.mount('#app');",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "fa-vue-composables",
      type: "code",
      source: [
        "// Vue Composables",
        "import {",
        "  useNotebookEngine,",
        "  provideNotebookEngine,",
        "  useNotebook,",
        "  useCell,",
        "  useFocusedCell,",
        "  NotebookEngineKey,",
        "} from '@velo-sci/notebook-vue';",
        "",
        "// Provide the engine at the root of your component tree",
        "provideNotebookEngine(engine);",
        "",
        "// Access the engine from any child component",
        "const engine = useNotebookEngine();",
        "",
        "// Reactive notebook state",
        "const notebook = useNotebook(engine);",
        "",
        "// Reactive cell state",
        "const cell = useCell(engine, 'cell-id');",
        "",
        "// Reactive focused cell ID",
        "const focusedId = useFocusedCell(engine);",
        "",
        "// Injection Key (Vue provide/inject)",
        "import { inject } from 'vue';",
        "const engine2 = inject(NotebookEngineKey);",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "fa-svelte-title",
      type: "markdown",
      source: [
        "## Svelte 5+ Adapter (`@velo-sci/notebook-svelte`)",
        "",
        "The Svelte adapter provides an imperative mounting class and Svelte-compatible stores.",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "fa-svelte-code",
      type: "code",
      source: [
        "// Svelte — imperative mounting",
        "import { SciNotebookSvelte } from '@velo-sci/notebook-svelte';",
        "",
        "const nb = new SciNotebookSvelte({",
        "  target: document.getElementById('notebook'),",
        "  notebook: myNotebook,",
        "  theme: 'dark',",
        "  onChange: (nb) => console.log('Updated:', nb),",
        "});",
        "",
        "// Update options",
        "nb.setTheme('light');",
        "",
        "// Destroy",
        "nb.destroy();",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "fa-svelte-stores",
      type: "code",
      source: [
        "// Svelte Stores (Readable<T> compatible)",
        "import { createNotebookStore } from '@velo-sci/notebook-svelte';",
        "import { createNotebook } from '@velo-sci/notebook-core';",
        "",
        "const engine = createNotebook({ notebook: myNotebook });",
        "const store = createNotebookStore(engine);",
        "",
        "// Svelte $store syntax",
        "$: notebook = $store.notebook;",
        "$: cells = $store.cells;",
        "$: focusedCellId = $store.focusedCellId;",
        "",
        "// Implements Svelte's Readable<T> interface —",
        "// works with $store auto-subscription syntax",
      ].join("\n"),
      metadata: { language: "svelte" },
    },
    {
      id: "fa-vanilla-title",
      type: "markdown",
      source: [
        "## Vanilla JS Adapter (`@velo-sci/notebook-vanilla`)",
        "",
        "For environments without a framework (plain HTML pages, web components, etc.).",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "fa-vanilla-code",
      type: "code",
      source: [
        "import { SciNotebookVanilla } from '@velo-sci/notebook-vanilla';",
        "",
        "const nb = new SciNotebookVanilla({",
        "  target: document.getElementById('notebook'),",
        "  notebook: myNotebook,",
        "  theme: 'dark',",
        "  showToolbar: true,",
        "  showTOC: true,",
        "  readOnly: false,",
        "  onChange: (notebook) => {",
        "    localStorage.setItem('notebook', JSON.stringify(notebook));",
        "  },",
        "});",
        "",
        "// Access the underlying engine",
        "const engine = nb.engine;",
        "",
        "// Update theme",
        "nb.setTheme('light');",
        "",
        "// Destroy and clean up DOM",
        "nb.destroy();",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "fa-vanilla-features",
      type: "markdown",
      source: [
        "### Built-in Features",
        "",
        "- **`DOMCellRenderer`** — Renders cells to DOM using the rendering pipeline",
        "- **`DragDropManager`** — Drag-and-drop cell reordering with visual indicators",
        "- **`KeyboardHandler`** — Full keyboard navigation (Escape, Enter, Shift+Enter, arrows, Ctrl+Z/Y/D)",
        "- **TOC sidebar** — Table of contents from headings",
        "- **Toolbar** — Cell type buttons, undo/redo, theme toggle",
        "- **Insert handles** — `+` buttons between cells",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "fa-vanilla-dom",
      type: "code",
      source: [
        "<!-- Vanilla adapter DOM structure -->",
        '<div class="sci-nb" data-theme="dark">',
        '  <div class="sci-nb-toolbar">',
        "    <!-- Toolbar buttons -->",
        "  </div>",
        '  <div class="sci-nb-cells">',
        '    <div class="sci-nb-cell sci-nb-cell--markdown sci-nb-cell--view"',
        '         data-cell-id="cell_abc">',
        '      <div class="sci-nb-cell-handle">⋮⋮</div>',
        '      <div class="sci-nb-cell-badge">MD</div>',
        '      <div class="sci-nb-cell-content">',
        "        <!-- Rendered HTML or textarea -->",
        "      </div>",
        '      <div class="sci-nb-cell-actions">',
        "        <!-- Delete, move up/down, type change -->",
        "      </div>",
        "    </div>",
        "    <!-- More cells... -->",
        '    <div class="sci-nb-add-cell">',
        "      <button>+ Add Cell</button>",
        "    </div>",
        "  </div>",
        "</div>",
      ].join("\n"),
      metadata: { language: "html" },
    },
    {
      id: "fa-arch",
      type: "mermaid",
      source: "graph TD\n  A[notebook-core] --> B[notebook-react]\n  A --> C[notebook-vue]\n  A --> D[notebook-svelte]\n  A --> E[notebook-vanilla]\n  A --> F[notebook-renderer]\n  F --> B\n  F --> C\n  F --> D\n  F --> E",
      metadata: {},
    },
    {
      id: "fa-theming-title",
      type: "markdown",
      source: [
        "## Theming",
        "",
        "Themes are implemented via CSS custom properties. The core ships with `light` and `dark` themes.",
        "Custom themes override these variables.",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "fa-theming-css",
      type: "code",
      source: [
        "/* Dark theme — CSS custom properties */",
        ".sci-nb[data-theme='dark'] {",
        "  --sci-nb-bg: #1a1a2e;",
        "  --sci-nb-bg-cell: #16213e;",
        "  --sci-nb-bg-cell-hover: #1a2744;",
        "  --sci-nb-bg-cell-focused: #0f3460;",
        "  --sci-nb-bg-toolbar: #0f0f23;",
        "  --sci-nb-border: #2a2a4a;",
        "  --sci-nb-border-focused: #4a6fa5;",
        "  --sci-nb-text: #e0e0e0;",
        "  --sci-nb-text-dim: #8888aa;",
        "  --sci-nb-text-heading: #ffffff;",
        "  --sci-nb-accent: #4a9eff;",
        "  --sci-nb-accent-hover: #6ab0ff;",
        "  --sci-nb-error: #ff6b6b;",
        "  --sci-nb-success: #51cf66;",
        "  --sci-nb-warning: #ffd43b;",
        '  --sci-nb-font-body: "Inter", -apple-system, sans-serif;',
        '  --sci-nb-font-mono: "JetBrains Mono", "Fira Code", monospace;',
        "  --sci-nb-font-size: 14px;",
        "  --sci-nb-line-height: 1.7;",
        "  --sci-nb-cell-padding: 16px;",
        "  --sci-nb-cell-radius: 8px;",
        "  --sci-nb-cell-gap: 8px;",
        "  --sci-nb-toolbar-height: 44px;",
        "  --sci-nb-ghost-text-color: #555577;",
        "}",
      ].join("\n"),
      metadata: { language: "css" },
    },
    {
      id: "fa-theming-custom",
      type: "code",
      source: [
        "// Custom theme — override any CSS variable",
        "const myTheme = {",
        '  "--sci-nb-bg": "#0d1117",',
        '  "--sci-nb-accent": "#58a6ff",',
        "  \"--sci-nb-font-body\": \"'IBM Plex Sans', sans-serif\",",
        "};",
        "",
        "<SciNotebook theme={myTheme} />",
      ].join("\n"),
      metadata: { language: "tsx" },
    },
    {
      id: "fa-toolbar",
      type: "markdown",
      source: [
        "## Toolbar API",
        "",
        "The toolbar is rendered by the adapter. It combines built-in actions with plugin-provided toolbar items.",
        "",
        "### Built-in Toolbar Groups",
        "",
        "| Group | Items |",
        "|-------|-------|",
        "| `file` | Save, Export |",
        "| `edit` | Undo, Redo |",
        "| `insert` | Add Markdown, Add Code, Add Raw (+ plugin items) |",
        "| `format` | Bold, Italic, Strikethrough, Code, Link, Heading |",
        "| `view` | Toggle all edit/view, Toggle toolbar, Theme switch |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "fa-toolbar-code",
      type: "code",
      source: [
        "// Toolbar Customization",
        "<SciNotebook",
        "  showToolbar={true}",
        "  toolbarItems={[",
        "    {",
        '      id: "my-export",',
        '      label: "Export PDF",',
        '      icon: "<svg>...</svg>",',
        '      group: "file",',
        "      action: () => exportToPDF(notebook),",
        "    },",
        "  ]}",
        "  // Hide specific built-in groups",
        '  toolbarGroups={["edit", "insert", "format", "view"]}',
        "/>",
      ].join("\n"),
      metadata: { language: "tsx" },
    },
    {
      id: "fa-a11y",
      type: "markdown",
      source: [
        "## Accessibility",
        "",
        "- All interactive elements have **ARIA labels**",
        "- Keyboard navigation follows **WAI-ARIA** patterns",
        "- Cell focus is managed with `tabindex` and `aria-activedescendant`",
        "- Screen reader **announcements** for cell operations (created, deleted, moved)",
        "- **High contrast mode** supported via CSS custom properties",
        "- **Reduced motion** respected via `prefers-reduced-motion` media query",
      ].join("\n"),
      metadata: {},
    },
  ],
  metadata: { author: "sci-notebook-docs" },
  version: 1,
  createdAt: "2025-01-01T00:00:00.000Z",
  updatedAt: "2025-01-01T00:00:00.000Z",
};
