export const latexMermaidNotebook = {
  metadata: { title: "LaTeX, Mermaid & Embeds", created: Date.now() },
  cells: [
    {
      id: "lm-1",
      type: "markdown",
      source: [
        "## LaTeX Support",
        "",
        "Inline math: $E = mc^2$ renders inline.",
        "",
        "Display math:",
        "",
        "$$\\\\int_0^\\\\infty e^{-x}\\\\,dx = 1$$",
        "",
        "Powered by **KaTeX** — 10x faster than MathJax, no layout reflows.",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "lm-2",
      type: "latex",
      source: "$$\\\\sum_{n=1}^{\\\\infty} \\\\frac{1}{n^2} = \\\\frac{\\\\pi^2}{6}$$",
      metadata: {},
      outputs: [],
    },
    {
      id: "lm-3",
      type: "markdown",
      source: [
        "## Mermaid Diagrams",
        "",
        "Supported types: flowchart, sequence, class, state, ER, gantt, pie, git graph, mindmap, timeline.",
        "",
        "Diagrams match the notebook theme (dark/light) and are rendered lazily.",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "lm-4",
      type: "mermaid",
      source: "graph TD\n  A[Start] --> B{Decision}\n  B -->|Yes| C[Process]\n  B -->|No| D[End]\n  C --> D",
      metadata: {},
      outputs: [],
    },
    {
      id: "lm-5",
      type: "markdown",
      source: [
        "## Embeds",
        "",
        "Three strategies:",
        "",
        "| Strategy | Description | Sandboxed? |",
        "|----------|-------------|------------|",
        "| `html` | Raw HTML (sanitized) | No |",
        "| `iframe` | External content | Yes |",
        "| `component` | Framework components | Trusted |",
        "",
        "All plugins follow the dual-mode pattern: **Edit** shows raw source, **View** shows rendered output.",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
  ],
};
