export const mathEditorNotebook = {
  id: "doc-math-editor",
  title: "Visual Formula Editor",
  cells: [
    {
      id: "me-intro",
      type: "markdown",
      source: [
        "# Visual Formula Editor (MathEditor)",
        "",
        "The MathEditor is a **visual LaTeX formula editor** with a clickable block palette,",
        "real-time KaTeX preview, and dual mode (visual/raw). It activates automatically when editing a LaTeX cell.",
        "",
        "## How It Works",
        "",
        "1. **Create a LaTeX cell** (from the `+` menu or by changing a cell's type)",
        "2. **Click** on the cell to open the MathEditor",
        "3. **Select a category** from the tab bar",
        "4. **Click a block** to insert it into the formula",
        "5. **Toggle** between Preview (visual) and LaTeX (raw) mode",
        "6. **Escape** to exit and see the rendered result",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-demo",
      type: "latex",
      source: "$$\n\\sum_{n=1}^{\\infty} \\frac{1}{n^2} = \\frac{\\pi^2}{6}\n$$",
      metadata: {},
    },
    {
      id: "me-categories",
      type: "markdown",
      source: [
        "## Block Categories",
        "",
        "The palette provides **9 categories** with 100+ symbols and structures:",
        "",
        "| Category | Examples | Count |",
        "|----------|----------|-------|",
        "| **Structures** | Fraction, root, superscript, subscript, hat, bar, vec | 8 |",
        "| **Integrals** | Integral, definite, double, triple, contour | 10 |",
        "| **Summations** | Summation, product, limit, inf, sup | 12 |",
        "| **Matrices** | 2x2, 3x3 in pmatrix, bmatrix, vmatrix, cases | 8 |",
        "| **Greek** | alpha, beta, gamma, delta, through Omega | 24 |",
        "| **Operators** | plus-minus, times, div, leq, geq, nabla | 20 |",
        "| **Arrows** | right, left, bidirectional, double arrows | 12 |",
        "| **Functions** | sin, cos, tan, log, ln, exp, det | 15 |",
        "| **Delimiters** | auto-sized parens, brackets, braces, norm | 10 |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-structures",
      type: "markdown",
      source: [
        "### Structures",
        "",
        "| Block | LaTeX | Description |",
        "|-------|-------|-------------|",
        "| Fraction | `\\frac{a}{b}` | Vertical fraction |",
        "| Root | `\\sqrt{x}` | Square root |",
        "| Superscript | `x^{n}` | Power / exponent |",
        "| Subscript | `x_{i}` | Index |",
        "| Hat | `\\hat{x}` | Hat accent |",
        "| Bar | `\\bar{x}` | Bar accent |",
        "| Vec | `\\vec{x}` | Vector arrow |",
        "| Tilde | `\\tilde{x}` | Tilde accent |",
        "| Dot | `\\dot{x}` | Time derivative |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-integrals-sums",
      type: "markdown",
      source: [
        "### Integrals",
        "",
        "| Block | LaTeX |",
        "|-------|-------|",
        "| Integral | `\\int f(x)\\,dx` |",
        "| Definite | `\\int_{a}^{b} f(x)\\,dx` |",
        "| Double | `\\iint f\\,dA` |",
        "| Triple | `\\iiint f\\,dV` |",
        "| Contour | `\\oint f\\,ds` |",
        "",
        "### Summations",
        "",
        "| Block | LaTeX |",
        "|-------|-------|",
        "| Summation | `\\sum_{i=0}^{n} a_i` |",
        "| Product | `\\prod_{i=1}^{n} x_i` |",
        "| Limit | `\\lim_{x \\to 0} f(x)` |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-greek-ops",
      type: "markdown",
      source: [
        "### Greek Letters (25 symbols)",
        "",
        "**Lowercase:** α β γ δ ε ζ η θ ι κ λ μ ν ξ π ρ σ τ υ φ χ ψ ω",
        "",
        "**Uppercase:** Γ Δ Θ Λ Ξ Π Σ Φ Ψ Ω",
        "",
        "### Operators (26 symbols)",
        "",
        "± × ÷ · ∘ ⊕ ⊗ ∂ ∇ ∞ ≈ ≠ ≡ ≤ ≥ ≪ ≫ ∈ ∉ ⊂ ⊃ ⊆ ∪ ∩ ∀ ∃",
        "",
        "### Arrows",
        "",
        "→ ← ↔ ⇒ ⇐ ⇔ ↦ ↑ ↓",
        "",
        "### Functions",
        "",
        "sin cos tan log ln exp lim max min det",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-delimiters",
      type: "markdown",
      source: [
        "### Delimiters",
        "",
        "| Block | LaTeX |",
        "|-------|-------|",
        "| Parentheses | `\\left( x \\right)` |",
        "| Brackets | `\\left[ x \\right]` |",
        "| Braces | `\\left\\\\{ x \\right\\\\}` |",
        "| Absolute value | single bars |",
        "| Norm | double bars |",
        "| Floor | `\\lfloor x \\rfloor` |",
        "| Ceiling | `\\lceil x \\rceil` |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-modes",
      type: "markdown",
      source: [
        "## Dual Mode",
        "",
        "### Preview Mode (default)",
        "- Shows the formula rendered with KaTeX in real time",
        "- Click on the block palette to insert symbols at cursor position",
        "- Visual feedback for the current formula",
        "",
        "### Raw LaTeX Mode",
        "- Direct editing of the LaTeX source code",
        "- Monospaced font for precise editing",
        "- Ideal for fine-tuning or pasting existing LaTeX",
        "- Palette blocks are inserted at the cursor position",
        "",
        "## Smart Insertion",
        "",
        "When you click a block in the palette:",
        "",
        "1. **No selection**: Block inserted at cursor position (raw) or appended (preview)",
        "2. **With selection**: Selected text replaces the first placeholder in the block",
        "3. **Auto-cursor**: Cursor moves to the first empty placeholder after insertion",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-katex",
      type: "markdown",
      source: [
        "## KaTeX Integration",
        "",
        "The MathEditor uses KaTeX for real-time preview. To enable it:",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-katex-code",
      type: "code",
      source: [
        "// In your entry point (main.tsx)",
        'import katex from "katex";',
        '"katex/dist/katex.min.css";',
        "",
        "(globalThis as any).katex = katex;",
        "",
        "// Without KaTeX, the preview shows the LaTeX code",
        "// in a styled font as a fallback.",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "me-shortcuts",
      type: "markdown",
      source: [
        "## Keyboard Shortcuts",
        "",
        "| Shortcut | Action |",
        "|----------|--------|",
        "| `Escape` | Exit editor, return to view mode |",
        "| `Shift+Enter` | Exit and move to next cell |",
        "| `Ctrl+Z` | Undo last change |",
        "| `Ctrl+Shift+Z` | Redo |",
      ].join("\n"),
      metadata: {},
    },
    {
      id: "me-api",
      type: "code",
      source: [
        "// MathEditor React component API",
        "import { MathEditor } from '@velo-sci/notebook-react';",
        "",
        "interface MathEditorProps {",
        "  cellId: string;       // Cell ID",
        "  source: string;       // LaTeX code (with $$ wrappers)",
        "  onExit: () => void;   // Callback when exiting",
        "}",
        "",
        "// The MathEditor is used internally by the Cell component",
        "// when a LaTeX cell enters edit mode.",
        "// You rarely need to use it directly.",
      ].join("\n"),
      metadata: { language: "typescript" },
    },
    {
      id: "me-matrix",
      type: "latex",
      source: "$$\n\\mathbf{A} = \\begin{pmatrix} a_{11} & a_{12} & \\cdots & a_{1n} \\\\ a_{21} & a_{22} & \\cdots & a_{2n} \\\\ \\vdots & \\vdots & \\ddots & \\vdots \\\\ a_{m1} & a_{m2} & \\cdots & a_{mn} \\end{pmatrix}\n$$",
      metadata: {},
    },
    {
      id: "me-formulas-title",
      type: "markdown",
      source: "## Formula Examples\n\nBelow are live rendered LaTeX cells demonstrating a variety of formulas:",
      metadata: {},
    },
    {
      id: "me-desc-quadratic",
      type: "markdown",
      source: "**Quadratic Formula** — The solution to the quadratic equation $ax^2 + bx + c = 0$.",
      metadata: {},
    },
    {
      id: "me-quadratic",
      type: "latex",
      source: "$$\nx = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}\n$$",
      metadata: {},
    },
    {
      id: "me-desc-gaussian",
      type: "markdown",
      source: "**Gaussian Integral** — A standard integral in statistics and physics.",
      metadata: {},
    },
    {
      id: "me-gaussian",
      type: "latex",
      source: "$$\n\\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}\n$$",
      metadata: {},
    },
    {
      id: "me-desc-taylor",
      type: "markdown",
      source: "**Taylor Series** — Expansion of a function into an infinite sum of terms.",
      metadata: {},
    },
    {
      id: "me-taylor",
      type: "latex",
      source: "$$\nf(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n\n$$",
      metadata: {},
    },
    {
      id: "me-desc-schrodinger",
      type: "markdown",
      source: "**Schrödinger Equation** — The fundamental equation of quantum mechanics.",
      metadata: {},
    },
    {
      id: "me-schrodinger",
      type: "latex",
      source: "$$\ni\\hbar\\frac{\\partial}{\\partial t}\\Psi(\\vec{r},t) = \\hat{H}\\Psi(\\vec{r},t)\n$$",
      metadata: {},
    },
    {
      id: "me-desc-euler",
      type: "markdown",
      source: "**Euler's Identity** — Often considered the most beautiful equation in mathematics.",
      metadata: {},
    },
    {
      id: "me-euler",
      type: "latex",
      source: "$$\ne^{i\\pi} + 1 = 0\n$$",
      metadata: {},
    },
    {
      id: "me-desc-fourier",
      type: "markdown",
      source: "**Fourier Transform** — Decomposes a function into its constituent frequencies.",
      metadata: {},
    },
    {
      id: "me-fourier",
      type: "latex",
      source: "$$\n\\hat{f}(\\xi) = \\int_{-\\infty}^{\\infty} f(x) e^{-2\\pi i x \\xi} dx\n$$",
      metadata: {},
    },
    {
      id: "me-desc-rotation",
      type: "markdown",
      source: "**Rotation Matrix** — Rotates a point in 2D space by an angle $\\theta$.",
      metadata: {},
    },
    {
      id: "me-rotation",
      type: "latex",
      source: "$$\nR(\\theta) = \\begin{pmatrix} \\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta \\end{pmatrix}\n$$",
      metadata: {},
    },
    {
      id: "me-desc-maxwell",
      type: "markdown",
      source: "**Maxwell's Equation (Faraday's Law)** — Describes how a magnetic field interacts with an electric circuit.",
      metadata: {},
    },
    {
      id: "me-maxwell",
      type: "latex",
      source: "$$\n\\nabla \\times \\vec{E} = -\\frac{\\partial \\vec{B}}{\\partial t}\n$$",
      metadata: {},
    },
    {
      id: "me-data",
      type: "markdown",
      source: [
        "## Data Format",
        "",
        "LaTeX cells store the LaTeX code wrapped in double-dollar-sign delimiters.",
        "The MathEditor automatically strips the delimiters when entering edit mode",
        "and adds them back on save. Whitespace and newlines are handled correctly.",
      ].join("\n"),
      metadata: {},
    },
  ],
  metadata: { author: "sci-notebook-docs" },
  version: 1,
  createdAt: "2025-01-01T00:00:00.000Z",
  updatedAt: "2025-01-01T00:00:00.000Z",
};
