export const performanceNotebook = {
  metadata: { title: "Performance & Optimization", created: Date.now() },
  cells: [
    {
      id: "pf-1",
      type: "markdown",
      source: [
        "## Performance Budget",
        "",
        "| Metric | Target |",
        "|--------|--------|",
        "| Initial load (core) | under 50 KB gzipped |",
        "| Time to interactive | under 200 ms |",
        "| Cell render (cached) | under 1 ms |",
        "| Cell render (cold) | under 10 ms |",
        "| Keystroke latency | under 16 ms |",

        "| 500 cells | Smooth scrolling |",
        "| 2000 cells | Usable |",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "pf-2",
      type: "markdown",
      source: [
        "## Virtual Rendering",
        "",
        "For notebooks with many cells, only visible cells are mounted to the DOM:",
        "",
        "```",
        "┌─────────────────────────┐",
        "│  Spacer (top)           │ ← unmounted cells",
        "│  Cell N   (mounted)     │",
        "│  Cell N+1 (mounted)     │ ← viewport + overscan",
        "│  Cell N+2 (mounted)     │",
        "│  Spacer (bottom)        │ ← unmounted cells",
        "└─────────────────────────┘",
        "```",
        "",
        "Activated when notebook exceeds **50 cells** (configurable).",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "pf-3",
      type: "code",
      source: [
        "// Content-addressed LRU cache",
        "function cacheKey(cell: Cell): string {",
        '  return fnv1a(`${cell.type}:${cell.source}:${cell.metadata.language || ""}`);',
        "}",
        "",
        "// Fast, non-cryptographic hash",
        "// Only that cell is invalidated on source change",
        "// Full cache clear on plugin/theme change",
      ].join("\n"),
      metadata: { language: "typescript" },
      outputs: [],
    },
    {
      id: "pf-4",
      type: "markdown",
      source: [
        "## Bundle Size",
        "",
        "| Package | Size (gzipped) |",
        "|---------|----------------|",
        "| `core` | ~15 KB |",
        "| `renderer` | ~25 KB |",
        "| `react` adapter | ~12 KB |",
        "| **Total** | **~52 KB** |",
        "",
        "Plugins load on demand: LaTeX (~90 KB), Mermaid (~180 KB).",
      ].join("\n"),
      metadata: {},
      outputs: [],
    },
    {
      id: "pf-5",
      type: "code",
      source: [
        "// Structural sharing for undo history",
        "// Only modified cells are cloned",
        "history.push({",
        "  ...notebook,",
        "  cells: notebook.cells.map((cell, i) =>",
        "    i === changedIndex",
        "      ? { ...cell, source: newSource }",
        "      : cell  // shared reference",
        "  ),",
        "});",
      ].join("\n"),
      metadata: { language: "typescript" },
      outputs: [],
    },
  ],
};
