import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introducción',
      items: [
        'guide/overview',
        'guide/data-model',
        'guide/editor-engine',
      ],
    },
    {
      type: 'category',
      label: 'Funcionalidades',
      items: [
        'guide/rendering-pipeline',
        'guide/plugin-system',
        'guide/latex-mermaid',
      ],
    },
    {
      type: 'category',
      label: 'Avanzado',
      items: [
        'guide/ai-integration',
        'guide/framework-adapters',
        'guide/performance',
      ],
    },
    {
      type: 'doc',
      id: 'roadmap',
      label: 'Roadmap',
    },
    {
      type: 'doc',
      id: 'COMPETITIVE_STUDY',
      label: 'Estudio Competitivo',
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    }
  ],
  examplesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'examples',
    }
  ]
};

export default sidebars;
